---
title: '-'
output: 
  html_document: 
    css: ~/my_lab/my-lab_folder/resources/rmark.css
date: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)

library(tidyverse)
library(hrbrthemes)
library(ggtext)
theme_set(
  # theme_ipsum_rc(grid = 'XY') +
  theme_minimal() +
    theme(
      plot.title.position = "plot",
      plot.margin = margin(25,25,25,25),
      axis.title.x = element_markdown(hjust = .5, size = 12, margin = margin(10,0,0,0)),
      axis.title.y = element_markdown(hjust = .5, size = 12, margin = margin(0,10,0,0)),
      plot.subtitle = element_markdown(family = 'Roboto Condensed', color = 'grey60')
    )
)
```



```{r}
# MANE data
mane_exons <-
  read_tsv('input/mane_exons.gtf',
           col_names = c('chr','source','feature','start','end','dot','strand','dot2','annotation'),
           show_col_types = FALSE) %>%
  select(chr,start,end,strand,annotation) %>%
  mutate(gene_id   = stringr::str_replace(annotation, '.*gene_id "([^.]*).*','\\1')) %>%
  mutate(gene_name = stringr::str_replace(annotation, '.*gene_name "([^"]*).*','\\1')) %>%
  mutate(exon_number = str_replace(annotation, '.*exon_number ([^;]*).*','\\1') %>% as.numeric()) %>%
  select(-annotation) %>%
  group_by(gene_name, exon_number) %>%
  filter(n() == 1) %>%
  ungroup() %>%
  mutate(id_intron_start = glue::glue('{chr}_{strand}_{end+1}')) %>%
  mutate(id_intron_end = glue::glue('{chr}_{strand}_{start-1}'))

```

```{r}
# U251
sj_data <- tibble()
for (filename in list.files('input/',full.names = TRUE, pattern = '.*SJ.out.tab')) {
  sj_data <- 
    bind_rows(
      sj_data,
      read_tsv(filename,
          col_names = c('chr', 'intron_start', 'intron_end', 'strand',
                        'intron_motif', 'annotated', 'uniq_map_reads',
                        'mult_map_reads', 'max_spliced_overhang'),
          show_col_types = FALSE) %>%
      mutate(strand = case_when(
        strand == 0 ~ 'undefined',
        strand == 1 ~ '+',
        strand == 2 ~ '-',
        TRUE ~ 'error'
      )) %>%
    mutate(from_file = basename(filename) %>% str_replace('[^_]*_([^_]*).*','\\1'))
    ) 
} 

sj_data <- sj_data %>%
  select(-annotated, -mult_map_reads, -max_spliced_overhang, -intron_motif) %>%
  pivot_wider(values_from = uniq_map_reads, names_from = from_file, values_fill = 0)

sj_data <-
  sj_data %>%
  mutate(id_intron_start = glue::glue('{chr}_{strand}_{intron_start}')) %>%
  mutate(id_intron_end  = glue::glue('{chr}_{strand}_{intron_end}')) %>%
  left_join(mane_exons %>%  
              select(gene_name, gene_id, exon_number, id_intron_start) %>%
              rename(from_exon = 'exon_number'),
            by = 'id_intron_start') %>%
  left_join(mane_exons %>% 
              select(exon_number, id_intron_end) %>%
              rename(to_exon = 'exon_number'),
            by = 'id_intron_end') %>%
  na.omit(.) %>%
  mutate(control_counts = C1 + C3 + C4) %>%
  mutate(kd_counts = KD1 + KD3 + KD4) %>%
  mutate(number_of_skipped_exons = abs(to_exon - from_exon) - 1)

sj_longer_u251 <- 
  sj_data %>%
  pivot_longer(names_to = 'condition', values_to = 'reads', c(control_counts, kd_counts)) %>%
  left_join(mane_exons %>% group_by(gene_id) %>% slice_max(exon_number) %>% distinct(gene_id, exon_number) %>% rename(max_exons = 'exon_number')) %>%
  select(-starts_with('C[0-9]'),-starts_with('KD')) %>%
  mutate(cell = 'U251')

### U343 ###############
sj_data <- tibble()
for (filename in list.files('input_343/',full.names = TRUE, pattern = '.*SJ.out.tab')) {
  sj_data <- 
    bind_rows(
      sj_data,
      read_tsv(filename,
          col_names = c('chr', 'intron_start', 'intron_end', 'strand',
                        'intron_motif', 'annotated', 'uniq_map_reads',
                        'mult_map_reads', 'max_spliced_overhang'),
          show_col_types = FALSE) %>%
      mutate(strand = case_when(
        strand == 0 ~ 'undefined',
        strand == 1 ~ '+',
        strand == 2 ~ '-',
        TRUE ~ 'error'
      )) %>%
    mutate(from_file = basename(filename) %>% str_replace('[^_]*_([^_]*).*','\\1'))
    ) 
} 

sj_data <- sj_data %>%
  select(-annotated, -mult_map_reads, -max_spliced_overhang, -intron_motif) %>%
  pivot_wider(values_from = uniq_map_reads, names_from = from_file, values_fill = 0)

sj_data <-
  sj_data %>%
  mutate(id_intron_start = glue::glue('{chr}_{strand}_{intron_start}')) %>%
  mutate(id_intron_end  = glue::glue('{chr}_{strand}_{intron_end}')) %>%
  left_join(mane_exons %>%  
              select(gene_name, gene_id, exon_number, id_intron_start) %>%
              rename(from_exon = 'exon_number'),
            by = 'id_intron_start') %>%
  left_join(mane_exons %>% 
              select(exon_number, id_intron_end) %>%
              rename(to_exon = 'exon_number'),
            by = 'id_intron_end') %>%
  na.omit(.) %>%
  mutate(control_counts = C2 + C6 + C7) %>%
  mutate(kd_counts = KD2 + KD6 + KD7) %>%
  mutate(number_of_skipped_exons = abs(to_exon - from_exon) - 1)

sj_longer_u343 <- 
  sj_data %>%
  pivot_longer(names_to = 'condition', values_to = 'reads', c(control_counts, kd_counts)) %>%
  left_join(mane_exons %>% group_by(gene_id) %>% slice_max(exon_number) %>% distinct(gene_id, exon_number) %>% rename(max_exons = 'exon_number')) %>%
  select(-starts_with('C[0-9]'),-starts_with('KD')) %>%
  mutate(cell = 'U343')


### MERGE
sj_longer <-
  bind_rows(sj_longer_u251, sj_longer_u343) %>%
  select(-c(C1,C2,C3,C6,C7)) %>%
  filter((strand == '-' & from_exon <= 5) | (strand == '+' & (max_exons - from_exon) <= 5)) %>%
  mutate(number_of_skipped_exons = fct_lump_n(as.character(number_of_skipped_exons),5,other_level = '+5')) %>%
  filter(as.character(number_of_skipped_exons) != '+5')

```


```{r}
data2plot2 <-
  sj_longer %>%
  mutate(
    splice_type = case_when(
      abs(from_exon-to_exon) == 1 ~ 'no_skip',
      abs(from_exon-to_exon) == 2 ~ 'one',
      abs(from_exon-to_exon) > 2 ~ 'many',
      TRUE ~ 'Bad'
    )
  ) %>% 
  ungroup() %>%
  group_by(number_of_skipped_exons, condition, cell) %>%
  summarise(reads = sum(reads)) %>%
  ungroup() %>%
  group_by(condition, cell) %>%
  mutate(percent_reads = reads/sum(reads)) %>%
  filter(as.character(number_of_skipped_exons) != '0')
```


```{r}
data2plot3 <-
  sj_longer %>%
  mutate(
    splice_type = case_when(
      abs(from_exon-to_exon) == 1 ~ 'no_skip',
      abs(from_exon-to_exon) > 1 ~ 'skip',
      TRUE ~ 'Bad'
    )
  ) %>%
  group_by(gene_id, condition, cell, splice_type) %>%
  summarise(reads = sum(reads)) %>%
  filter(splice_type == 'skip') %>%
  # mutate(condition = condition %>% str_replace("_counts",'')) %>% 
  pivot_wider(names_from = condition, values_from = reads)

max_reads <- ((data2plot3$control_counts + data2plot3$kd_counts)/2) %>% quantile(0.90)

data2plot3 %>%
  filter(control_counts < max_reads & kd_counts < max_reads) %>%
  ggplot(aes(x = control_counts, y = kd_counts, color = abs(control_counts - kd_counts))) +
  geom_point() +
  geom_abline(color = 'grey40', alpha = 1) +
  facet_wrap(~cell) +
  viridis::scale_color_viridis(direction = 1) +
  theme(legend.position = 'bottom') +
  guides(color = guide_colorbar(title.position = "bottom", 
                                title.hjust = .5, 
                                barwidth = unit(20, "lines"), 
                                barheight = unit(.5, "lines"))) +
  labs(y = '**Skipping reads KD** (counts)', 
       x = '**Skipping reads Control** (counts)', 
       color = 'Distance Control-KD')
```